name: CI Pipeline - AppMonitor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza checkout do código
        uses: actions/checkout@v3

      - name: Valida a sintaxe do status-check.sh
        run: bash -n status-check.sh

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Simula os testes
        run: |
          echo "Running tests"
          exit 0

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Cria report.zip
        run: zip -r report.zip status-check.sh README.md

      - name: Faz o upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
