name: CI Pipeline - AppMonitor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza checkout do c칩digo
        uses: actions/checkout@v3

      - name: Valida a sintaxe do status-check.sh
        run: bash -n status-check.sh

      - name: Mensagens personalizadas
        run: |
          echo "::warning::Verifique se o script est치 atualizado"
          echo "::error::Erro simulado de exemplo (ignorado para testes)"

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Simula os testes
        run: |
          echo "Running tests"
          exit 0

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Cria report.zip
        run: zip -r report.zip status-check.sh README.md

      - name: Faz o upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip

      - name: Resumo do Job
        run: |
          echo "### Job Summary" >> $GITHUB_STEP_SUMMARY
          echo "* SO: $RUNNER_OS" >> $GITHUB_STEP_SUMMARY
          echo "* Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "* Artefato gerado: [report.zip](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
