name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ vars.PROD_DOMAIN }}
    steps:
      - name: Realiza o deploy
        run: echo "Deploying to ${{ vars.PROD_DOMAIN }}"
